# Conda environment configuration for Windows users with NVIDIA GPUs:
name: monet-cyclegan-cuda

channels:
  - conda-forge

dependencies:
  - python=3.8
  - pip
  - ipykernel
  - cudatoolkit
  - cudnn

  - pip:
      - tensorflow
      - tensorflow-addons
      - matplotlib
      - pillow
      - scipy
      - seaborn
