name: monet-cyclegan-macos

channels:
  - apple
  - conda-forge

dependencies:
  - python=3.9
  - pip
  - tensorflow-deps
  - ipykernel

  - pip:
      - tensorflow-macos==2.10
      - tensorflow-metal==0.6
      - tensorflow-addons
      - matplotlib
      - pillow
