name: monet-cyclegan-windows-nvidia

channels:
  - conda-forge

dependencies:
  - python=3.9
  - pip
  - ipykernel
  - cudatoolkit
  - cudnn

  - pip:
      - tensorflow
      - tensorflow-addons
      - matplotlib
      - pillow
