# Conda environment configuration for macOS users:
name: monet-cyclegan-macos

channels:
  - apple
  - conda-forge

dependencies:
  - python=3.8
  - pip
  - tensorflow-deps
  - ipykernel

  - pip:
      - tensorflow-macos==2.10
      - tensorflow-metal==0.6
      - tensorflow-addons
      - matplotlib
      - pillow
      - scipy
      - seaborn
      - pytorch-fid
